const HowToBidPage = () => {
	const sections = {
		registration: {
			title: "Registration and Verification:",
			steps: [
				"The first step in order to participate and have access to bidding in our auctions is to get yourself registered/create an account with us at www.alturaash.org and verify your personal details.",
				"Once you've registered, your system-generated password will be sent to you at the e-mail address you provided us with.",
				"Existing members will still be required to request approval to bid by clicking on the 'Register for Sale' button.",
				"Alturaash representative will then get in touch with you via email or phone to verify the details you provided.",
			],
		},
		notes: {
			title: "Please note that:",
			points: [
				"If the registration process is not completed and authenticated before the auction, your access to bid at any of our auctions will not be approved.",
				"It is recommended that all bidders register with us at least 24 hours before the auction.",
				"You will receive a confirmation via e-mail once your bidding access is approved.",
				"We are an online auction house, and all bidding takes place online only. Bids can be executed on any private computer, laptop, tablet, android, or i-phone device.",
			],
		},
		bidding: {
			title: "BIDDING",
			sections: [
				{
					title: "Online Bid:",
					content:
						"With our online auctions, you can bid directly from the comfort of your home, office, or on the move from anywhere in the world. Each online auction commences at 10:30 am UAE time on the date mentioned in the catalog in 'Upcoming Auctions'.",
				},
				{
					title: "Proxy / Maximum Bid:",
					content:
						"Once an auction catalog goes LIVE, a Proxy or Maximum Bid can be placed on any lot by visiting the upcoming auction tab on the website.",
				},
				{
					title: "Opening Bid:",
					content:
						"Opening bid is the value at which the bidding on a lot begins. It is at times lower than the lower estimate also.",
				},
			],
		},
	};

	return (
		<div className='max-w-6xl mx-auto px-4 py-16'>
			<h1 className='text-3xl font-light text-center mb-8'>HOW TO BID</h1>

			<p className='text-gray-700 mb-12'>
				The motivation to acquire a work of art is generated by the will
				of one's heart than by the mind or by the pocketbook. But for a
				first-time collector, bidding can get intimidating. The services
				we offer here at Alturaash make bidding easier and much more
				accessible for lovers of art.
			</p>

			{/* Registration Section */}
			<section className='mb-12'>
				<h2 className='text-xl font-medium mb-4'>
					{sections.registration.title}
				</h2>
				<ol className='list-decimal pl-5 space-y-4'>
					{sections.registration.steps.map((step, index) => (
						<li key={index} className='text-gray-700'>
							{step}
						</li>
					))}
				</ol>
			</section>

			{/* Notes Section */}
			<section className='mb-12'>
				<h2 className='text-xl font-medium mb-4'>
					{sections.notes.title}
				</h2>
				<ul className='list-disc pl-5 space-y-4'>
					{sections.notes.points.map((point, index) => (
						<li key={index} className='text-gray-700'>
							{point}
						</li>
					))}
				</ul>
			</section>

			{/* Auction Estimates */}
			<section className='mb-12'>
				<h2 className='text-xl font-medium mb-4'>Auction Estimates:</h2>
				<p className='text-gray-700'>
					Estimates are based on an indicative market value of the lot
					as determined by Alturaash auction specialists. Our
					estimates are always listed in United States Dollars (USD).
				</p>
			</section>

			{/* Reserves */}
			<section className='mb-12'>
				<h2 className='text-xl font-medium mb-4'>Reserves:</h2>
				<p className='text-gray-700'>
					The reserve price is the minimum price at which the lot
					shall be sold. It will remain confidential and will not be
					disclosed. It is always lower or equal to the lower
					estimated value of the artwork set by the auction house.
				</p>
			</section>

			{/* Buyer's Premium Section */}
			<section className='mb-12'>
				<h2 className='text-xl font-medium mb-4'>
					Buyer's Premium & Applicable Taxes:
				</h2>
				<ul className='list-disc pl-5 space-y-4'>
					<li className='text-gray-700'>
						10% buyer's premium will be added to the winning bid
						price.
					</li>
					<li className='text-gray-700'>
						No taxes are applicable on purchases from anywhere in
						the world except for The United Arab Emirates.
					</li>
					<li className='text-gray-700'>
						Value Added Tax (VAT) of 5% will be applicable on
						Alturaash's commission on purchases from within UAE.
					</li>
				</ul>
			</section>

			{/* Bidding Section */}
			<section className='mb-12'>
				<h2 className='text-2xl font-medium mb-6'>
					{sections.bidding.title}
				</h2>
				{sections.bidding.sections.map((section, index) => (
					<div key={index} className='mb-8'>
						<h3 className='text-lg font-medium mb-2'>
							{section.title}
						</h3>
						<p className='text-gray-700'>{section.content}</p>
					</div>
				))}
			</section>
		</div>
	);
};

export default HowToBidPage;
